# Generated by Django 4.2 on 2023-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomm',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
